### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by ashine-dissanayake** [uqembeddedsys-projects/csse4011_zephyr_guides#1]
https://github.com/uqembeddedsys-projects/csse4011_zephyr_guides/blob/c109689e95ae4376aa527e90b4a366b71abf03da/mkdocs/docs/Connectivity/CN.3-Serial_Console.md?plain=1#L101

There is a little typo on this line.

**Comment by twilfredo** [comment]
Hey,

Thanks for letting me know! I have fixed it in https://github.com/uqembeddedsys-projects/csse4011_zephyr_guides/commit/22c54f83dc0b4ed7a4dd1f61e17690b51f8a6ef5
